# TODO: colors
"$schema" = "https://starship.rs/config-schema.json"

palette = "nordic"
format = """
($os$hostname  )$username  ${custom.folder_symbol}$directory\
$fill\
$git_branch  $git_status\
$line_break $character
"""
right_format = "$cmd_duration"
continuation_prompt = "[â”ƒ]() "

[palettes.nordic]
black = "#191D24"
bright-black = "#242933"
grey = "#3B4252"
bright-grey = "#4C566A"
white = "#D8DEE9"
bright-white = "#E5E9F0"
blue = "#81A1C1"
bright-blue = "#88C0D0"
cyan = "#8FBCBB"
bright-cyan = "#93CCDC"
red = "#BF616A"
bright-red = "#D06F79"
orange = '#D08770'
bright-orange = '#D79784'
yellow = "#EBCB8B"
bright-yellow = "#F0D399"
green = "#A3BE8C"
bright-green = "#B1D196"
purple = "#B48EAD"
bright-purple = "#C895BF"

[os]
disabled = false
format = "[î‚¶](fg:yellow)[$symbol]($style)"
style = "fg:bright-black bg:yellow"

[os.symbols]
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœ"
Arch = "ó°£‡"
Artix = "ó°£‡"
CachyOS = "ó°£‡"
CentOS = "ïŒ„"
Debian = "ó°£š"
DragonFly = "î»¸"
Fedora = "ó°£›"
FreeBSD = "ó°±¯"
Gentoo = "ó°£¨"
Linux = "ó°Œ½"
Macos = "ó°€µ"
Manjaro = "ïŒ’"
Mint = "ó°£­"
NixOS = "ó±„…"
Raspbian = "ó°¿"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"
SUSE = "ïŒ”"
Ubuntu = "ó°•ˆ"
Unknown = "ï€‡"
Void = "ïŒ®"
Windows = "ó°² "

[hostname]
ssh_only = false
format = "[ $hostname ]($style)[î‚´](fg:yellow)"
style = "fg:bright-black bg:yellow"

[username]
format = "[î‚¶](fg:green)[ ï€‡ $user ]($style)[î‚´](fg:green)"
style_root = "fg:bright-black bg:green"
style_user = "fg:bright-black bg:green"
show_always = true

[custom.folder_symbol]
command = 'git rev-parse --is-inside-work-tree &>/dev/null && echo "ó°Š¢" || echo "ï»"'
format = "[î‚¶](fg:cyan)[ $output]($style)"
style = "fg:bright-black bg:cyan"
when = true

[directory]
format = "[ $path ($read_only )]($style)[î‚´](fg:cyan)"
style = "fg:bright-black bg:cyan"
read_only = "ó°Œ¾"
truncation_symbol = "â€¦/"

[fill]
symbol = " "

[git_branch]
format = "([î‚¶](fg:blue)[ $symbol $branch(:$remote_branch) ]($style)[î‚´](fg:blue))"
symbol ="îœ¥"
style = "fg:bright-black bg:blue"

[git_status]
format = "([î‚¶](fg:purple)[ $all_status$ahead_behind ]($style)[î‚´](fg:purple))"
style = "fg:bright-black bg:purple"
ahead = 'â‡¡ ${count}'
behind = 'â‡£ ${count}'
conflicted = 'ğŸ³ ${count}'
deleted = 'ï“– ${count}'
diverged = 'â‡• â‡¡${ahead_count}â‡£${behind_count} '
modified = 'ï“’ ${count}'
renamed = 'ï“• ${count}'
staged = 'ï“ $count'
stashed = "ï ${count}"
untracked = "ï“ ${count}"
up_to_date = ''

[cmd_duration]
format = "[$duration]($style)"
style = "fg:bright-grey"

[character]
success_symbol = "[âœ](fg:white)"
error_symbol = "[âœ](fg:white)"
vimcmd_symbol = "[âœ](fg:white)"
